### ISSUE TITLE
Negative Gfx clock

### ISSUE THREAD

**Issue by Mantas-2155X** [azeam/powerupp#17]
First of all, I'd like to start off by saying this is a great app and I love it.

**Issue:**
After overclocking the Gfx clock past 2146 MHz I noticed a small weird bug. The displayed Gfx clock in the top bar (not input fields) becomes -2144 MHz. Frequencies below 2147 MHz seem to work fine.

**Image of the issue:**
![image](https://i.imgur.com/SnVpCUi.png)

**System Information:**
GPU: ASUS ROG Strix RX 5700 XT
Distro: Kubuntu 20.04
Kernel: 5.8.5-tkg-pds
powerupp: Commit [2626c0a](https://github.com/azeam/powerupp/commit/2626c0a220b5e06fa1b9337911d1110d8ccb4dee)

**Comment by azeam** [comment]
Thanks for the report. Since it's exactly at that number I would guess the reason for this is that the hwmon temperatures are registered in hertz and you are hitting the 32 bit signed binary integer limit of 2,147,483,647, causing a negative reading (you can confirm it's the hwmon giving a false reading with `cat /sys/class/drm/card0/device/hwmon/$(ls -1 /sys/class/drm/card0/device/hwmon)/freq1_input` while hitting those values).

If that is the case I don't think it would make sense to display it otherwise in powerupp since the reading is not accurate anyway. You broke the system, go easy on that card ;)

**Comment by azeam** [comment]
Thanks for the report. Since it's exactly at that number I would guess the reason for this is that the hwmon frequencies are registered in hertz and you are hitting the C integer limit of 2,147,483,647, causing a negative reading. I changed it to an unsigned int which should fix this, I don't know if hwmon uses int though (you can check if hwmon is giving a false reading with `cat /sys/class/drm/card0/device/hwmon/$(ls -1 /sys/class/drm/card0/device/hwmon)/freq1_input` while hitting those values).

**Comment by Mantas-2155X** [comment]
Thank you for the quick fix. 
Just compiled with the latest commit and it seems to be fixed.

hwmon doesn't seem to have a false reading and works correctly.
`$ cat /sys/class/drm/card0/device/hwmon/$(ls -1 /sys/class/drm/card0/device/hwmon)/freq1_input`
`2150000000`
